-- =========================================================
-- Corporate Client Gap Agent - PostgreSQL schema v2.0
-- Purpose:
--   - Keep current RM plan data.
--   - Store consultation questions and answers.
--   - Reuse confirmed consultation answers as structured facts in later gap analyses.
--   - Preserve analysis-time snapshots and selected external evidence.
-- =========================================================

-- ---------------------------------------------------------
-- company: corporate client master
-- ---------------------------------------------------------
CREATE TABLE company (
    company_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_code         VARCHAR(8)   NOT NULL,
    corp_name         VARCHAR(200) NOT NULL,
    stock_code        VARCHAR(20),
    last_consulted_at TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_company_corp_code UNIQUE (corp_code),
    CONSTRAINT ck_company_corp_code CHECK (corp_code ~ '^[0-9]{8}$')
);

CREATE INDEX ix_company_corp_name ON company (corp_name);

COMMENT ON TABLE company IS 'Corporate client master. corp_code is the OpenDART company code.';

-- ---------------------------------------------------------
-- rm_plan: current RM-known plan information
-- ---------------------------------------------------------
CREATE TABLE rm_plan (
    plan_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT        NOT NULL,
    domain             VARCHAR(30)   NOT NULL,
    scope              TEXT,
    knowledge_status   VARCHAR(30)   NOT NULL,
    plan_status        VARCHAR(30)   NOT NULL,
    last_confirmed_at  TIMESTAMPTZ,
    amount             NUMERIC(20,2),
    currency           VARCHAR(3),
    expected_at        DATE,
    expected_precision VARCHAR(20),
    source             TEXT,
    evidence_level     VARCHAR(30),
    valid_until        DATE,
    review_due_at      DATE,
    validity_status    VARCHAR(30),
    recorded_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    note               TEXT,

    CONSTRAINT fk_rm_plan_company FOREIGN KEY (company_id)
        REFERENCES company (company_id) ON DELETE RESTRICT,

    CONSTRAINT ck_rm_plan_domain CHECK (domain IN ('INVESTMENT', 'FUNDING', 'FX')),
    CONSTRAINT ck_rm_plan_knowledge_status CHECK (
        knowledge_status IN ('EXPLICIT_YES', 'EXPLICIT_NONE', 'UNCONFIRMED', 'UNRECORDED')),
    CONSTRAINT ck_rm_plan_plan_status CHECK (
        plan_status IN ('REVIEW', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', 'NOT_APPLICABLE', 'UNKNOWN')),
    CONSTRAINT ck_rm_plan_expected_precision CHECK (
        expected_precision IS NULL OR expected_precision IN ('DAY', 'MONTH', 'QUARTER', 'HALF', 'YEAR')),
    CONSTRAINT ck_rm_plan_evidence_level CHECK (
        evidence_level IS NULL OR evidence_level IN ('DIRECT', 'DOCUMENT', 'INDIRECT', 'NONE')),
    CONSTRAINT ck_rm_plan_validity_status CHECK (
        validity_status IS NULL OR validity_status IN ('UNVERIFIED', 'NO_CHANGE_EVIDENCE', 'RECHECK_NEEDED', 'PENDING')),
    CONSTRAINT ck_rm_plan_amount CHECK (amount IS NULL OR amount >= 0),
    CONSTRAINT ck_rm_plan_currency CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_rm_plan_status_consistency CHECK (
           (knowledge_status = 'EXPLICIT_NONE' AND plan_status = 'NOT_APPLICABLE')
        OR (knowledge_status IN ('UNCONFIRMED', 'UNRECORDED') AND plan_status = 'UNKNOWN')
        OR (knowledge_status = 'EXPLICIT_YES' AND plan_status <> 'NOT_APPLICABLE')
    ),
    CONSTRAINT ck_rm_plan_unrecorded_empty CHECK (
        knowledge_status <> 'UNRECORDED'
        OR (last_confirmed_at IS NULL AND source IS NULL AND amount IS NULL)
    ),
    CONSTRAINT ck_rm_plan_amount_currency CHECK (amount IS NULL OR currency IS NOT NULL),
    CONSTRAINT ck_rm_plan_expected_with_precision CHECK (
        (expected_at IS NULL) = (expected_precision IS NULL))
);

CREATE INDEX ix_rm_plan_company_domain ON rm_plan (company_id, domain);
CREATE INDEX ix_rm_plan_review_due_at ON rm_plan (review_due_at);

COMMENT ON TABLE rm_plan IS 'Current RM-known plan information. Consultation answers are stored separately and may later update this table after RM confirmation.';

-- ---------------------------------------------------------
-- consultation: customer consultation session
-- ---------------------------------------------------------
CREATE TABLE consultation (
    consultation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT       NOT NULL,
    consulted_at    TIMESTAMPTZ  NOT NULL,
    channel         VARCHAR(30)  NOT NULL,
    consultant_name VARCHAR(100),
    memo            TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_consultation_company FOREIGN KEY (company_id)
        REFERENCES company (company_id) ON DELETE RESTRICT,
    CONSTRAINT ck_consultation_channel CHECK (
        channel IN ('VISIT', 'PHONE', 'EMAIL', 'VIDEO', 'OTHER'))
);

CREATE INDEX ix_consultation_company_at ON consultation (company_id, consulted_at DESC);

COMMENT ON TABLE consultation IS 'Consultation session with a corporate client.';

-- ---------------------------------------------------------
-- gap_analysis: analysis execution history
-- ---------------------------------------------------------
CREATE TABLE gap_analysis (
    analysis_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            BIGINT       NOT NULL,
    analysis_at           TIMESTAMPTZ  NOT NULL,
    query_start_at        TIMESTAMPTZ,
    query_end_at          TIMESTAMPTZ,
    query_ranges          JSONB,
    retrieval_status      VARCHAR(30)  NOT NULL,
    crm_snapshot          JSONB        NOT NULL,
    consultation_snapshot JSONB,
    rule_version          VARCHAR(30)  NOT NULL,
    model_version         VARCHAR(100),
    scope_limited         BOOLEAN      NOT NULL DEFAULT false,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_gap_analysis_company FOREIGN KEY (company_id)
        REFERENCES company (company_id) ON DELETE RESTRICT,

    CONSTRAINT ck_gap_analysis_retrieval_status CHECK (
        retrieval_status IN ('SUCCESS', 'PARTIAL_FAILURE', 'FAILURE')),
    CONSTRAINT ck_gap_analysis_query_range CHECK (
        query_start_at IS NULL OR query_end_at IS NULL OR query_start_at <= query_end_at),
    CONSTRAINT ck_gap_analysis_crm_snapshot_object CHECK (jsonb_typeof(crm_snapshot) = 'object'),
    CONSTRAINT ck_gap_analysis_consultation_snapshot_object CHECK (
        consultation_snapshot IS NULL OR jsonb_typeof(consultation_snapshot) = 'object'),
    CONSTRAINT ck_gap_analysis_query_ranges_array CHECK (
        query_ranges IS NULL OR jsonb_typeof(query_ranges) = 'array')
);

CREATE INDEX ix_gap_analysis_company_at ON gap_analysis (company_id, analysis_at DESC);

COMMENT ON TABLE gap_analysis IS 'Analysis run history with immutable input snapshots.';

-- ---------------------------------------------------------
-- gap_result: domain-level gap assessment result
-- ---------------------------------------------------------
CREATE TABLE gap_result (
    result_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id         BIGINT       NOT NULL,
    company_id          BIGINT       NOT NULL,
    plan_id             BIGINT,
    domain              VARCHAR(30)  NOT NULL,
    change_type         VARCHAR(30),
    change_detail       VARCHAR(30),
    assessment_status   VARCHAR(30)  NOT NULL,
    priority            SMALLINT,
    priority_reason     TEXT,
    changed_fields      JSONB,
    financial_signals   JSONB,
    environment_context JSONB,
    summary             TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_gap_result_analysis FOREIGN KEY (analysis_id)
        REFERENCES gap_analysis (analysis_id) ON DELETE RESTRICT,
    CONSTRAINT fk_gap_result_company FOREIGN KEY (company_id)
        REFERENCES company (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_gap_result_plan FOREIGN KEY (plan_id)
        REFERENCES rm_plan (plan_id) ON DELETE RESTRICT,

    CONSTRAINT ck_gap_result_domain CHECK (domain IN ('INVESTMENT', 'FUNDING', 'FX')),
    CONSTRAINT ck_gap_result_change_type CHECK (
        change_type IS NULL OR change_type IN ('CONFLICT', 'NEW_INFO', 'SPECIFIED', 'CANCELED_OR_COMPLETED', 'NEEDS_CONFIRMATION')),
    CONSTRAINT ck_gap_result_change_detail CHECK (
        change_detail IS NULL OR change_detail IN ('CANCELED', 'COMPLETED')),
    CONSTRAINT ck_gap_result_assessment_status CHECK (
        assessment_status IN ('CONFIRMED', 'PENDING', 'NO_CHANGE_EVIDENCE', 'RETRIEVAL_FAILED')),
    CONSTRAINT ck_gap_result_priority CHECK (priority IS NULL OR priority BETWEEN 1 AND 3),
    CONSTRAINT ck_gap_result_status_type CHECK (
           (assessment_status = 'CONFIRMED'
                AND COALESCE(change_type IN ('CONFLICT', 'NEW_INFO', 'SPECIFIED', 'CANCELED_OR_COMPLETED'), false))
        OR (assessment_status = 'PENDING'
                AND change_type IS NOT DISTINCT FROM 'NEEDS_CONFIRMATION')
        OR (assessment_status IN ('NO_CHANGE_EVIDENCE', 'RETRIEVAL_FAILED') AND change_type IS NULL)
    ),
    CONSTRAINT ck_gap_result_change_detail_usage CHECK (
        (change_type IS NOT DISTINCT FROM 'CANCELED_OR_COMPLETED') = (change_detail IS NOT NULL)
    ),
    CONSTRAINT ck_gap_result_plan_required CHECK (
        change_type NOT IN ('CONFLICT', 'SPECIFIED', 'CANCELED_OR_COMPLETED') OR plan_id IS NOT NULL
    )
);

CREATE INDEX ix_gap_result_analysis ON gap_result (analysis_id);
CREATE INDEX ix_gap_result_company_domain ON gap_result (company_id, domain);
CREATE INDEX ix_gap_result_plan ON gap_result (plan_id);

COMMENT ON TABLE gap_result IS 'Gap assessment result. Follow-up questions are stored in consultation_qa, not as JSON.';

-- ---------------------------------------------------------
-- consultation_qa: consultation question and answer
-- ---------------------------------------------------------
CREATE TABLE consultation_qa (
    qa_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consultation_id          BIGINT       NOT NULL,
    company_id               BIGINT       NOT NULL,
    plan_id                  BIGINT,
    generated_from_result_id BIGINT,
    question_source          VARCHAR(30)  NOT NULL,
    question_text            TEXT         NOT NULL,
    answer_status            VARCHAR(30)  NOT NULL DEFAULT 'UNANSWERED',
    answer_text              TEXT,
    answered_at              TIMESTAMPTZ,
    answered_by              VARCHAR(100),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_consultation_qa_consultation FOREIGN KEY (consultation_id)
        REFERENCES consultation (consultation_id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultation_qa_company FOREIGN KEY (company_id)
        REFERENCES company (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultation_qa_plan FOREIGN KEY (plan_id)
        REFERENCES rm_plan (plan_id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultation_qa_generated_from_result FOREIGN KEY (generated_from_result_id)
        REFERENCES gap_result (result_id) ON DELETE SET NULL,

    CONSTRAINT ck_consultation_qa_question_source CHECK (
        question_source IN ('AI_GENERATED', 'RM_MANUAL')),
    CONSTRAINT ck_consultation_qa_answer_status CHECK (
        answer_status IN ('UNANSWERED', 'ANSWERED', 'DECLINED', 'UNKNOWN', 'NEEDS_FOLLOWUP')),
    CONSTRAINT ck_consultation_qa_answered_fields CHECK (
           (answer_status = 'ANSWERED' AND answer_text IS NOT NULL AND answered_at IS NOT NULL)
        OR (answer_status <> 'ANSWERED')
    )
);

CREATE INDEX ix_consultation_qa_consultation ON consultation_qa (consultation_id);
CREATE INDEX ix_consultation_qa_company_plan ON consultation_qa (company_id, plan_id);
CREATE INDEX ix_consultation_qa_generated_result ON consultation_qa (generated_from_result_id);
CREATE INDEX ix_consultation_qa_answer_status ON consultation_qa (answer_status);

COMMENT ON TABLE consultation_qa IS 'Question and answer records. Stores both AI-generated and RM-manual questions.';

-- ---------------------------------------------------------
-- plan_fact: structured plan fact extracted from answers or RM input
-- ---------------------------------------------------------
CREATE TABLE plan_fact (
    fact_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT       NOT NULL,
    plan_id             BIGINT,
    qa_id               BIGINT,
    domain              VARCHAR(30)  NOT NULL,
    scope               TEXT,
    plan_status         VARCHAR(30)  NOT NULL,
    amount              NUMERIC(20,2),
    currency            VARCHAR(3),
    expected_at         DATE,
    expected_precision  VARCHAR(20),
    fact_source         VARCHAR(30)  NOT NULL,
    extraction_method   VARCHAR(30)  NOT NULL,
    verification_status VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    effective_from      TIMESTAMPTZ,
    confirmed_at        TIMESTAMPTZ,
    note                TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_plan_fact_company FOREIGN KEY (company_id)
        REFERENCES company (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_plan_fact_plan FOREIGN KEY (plan_id)
        REFERENCES rm_plan (plan_id) ON DELETE RESTRICT,
    CONSTRAINT fk_plan_fact_qa FOREIGN KEY (qa_id)
        REFERENCES consultation_qa (qa_id) ON DELETE RESTRICT,

    CONSTRAINT ck_plan_fact_domain CHECK (domain IN ('INVESTMENT', 'FUNDING', 'FX')),
    CONSTRAINT ck_plan_fact_plan_status CHECK (
        plan_status IN ('REVIEW', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', 'NOT_APPLICABLE', 'UNKNOWN')),
    CONSTRAINT ck_plan_fact_amount CHECK (amount IS NULL OR amount >= 0),
    CONSTRAINT ck_plan_fact_currency CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_plan_fact_amount_currency CHECK (amount IS NULL OR currency IS NOT NULL),
    CONSTRAINT ck_plan_fact_expected_precision CHECK (
        expected_precision IS NULL OR expected_precision IN ('DAY', 'MONTH', 'QUARTER', 'HALF', 'YEAR')),
    CONSTRAINT ck_plan_fact_expected_with_precision CHECK (
        (expected_at IS NULL) = (expected_precision IS NULL)),
    CONSTRAINT ck_plan_fact_source CHECK (
        fact_source IN ('CONSULTATION_ANSWER', 'RM_INPUT', 'DISCLOSURE', 'SYSTEM')),
    CONSTRAINT ck_plan_fact_extraction_method CHECK (
        extraction_method IN ('AI_EXTRACTED', 'RM_ENTERED', 'RULE_EXTRACTED')),
    CONSTRAINT ck_plan_fact_verification_status CHECK (
        verification_status IN ('PENDING', 'RM_CONFIRMED', 'REJECTED')),
    CONSTRAINT ck_plan_fact_confirmed_at CHECK (
           (verification_status = 'RM_CONFIRMED' AND confirmed_at IS NOT NULL)
        OR (verification_status <> 'RM_CONFIRMED')
    ),
    CONSTRAINT ck_plan_fact_source_reference CHECK (
        fact_source <> 'CONSULTATION_ANSWER' OR qa_id IS NOT NULL
    )
);

CREATE INDEX ix_plan_fact_company_domain_status ON plan_fact (company_id, domain, verification_status);
CREATE INDEX ix_plan_fact_plan ON plan_fact (plan_id);
CREATE INDEX ix_plan_fact_qa ON plan_fact (qa_id);

COMMENT ON TABLE plan_fact IS 'Structured plan facts extracted from consultation answers, RM input, disclosures, or system rules.';

-- ---------------------------------------------------------
-- external_evidence: selected external evidence used in analysis
-- ---------------------------------------------------------
CREATE TABLE external_evidence (
    evidence_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT       NOT NULL,
    source_system      VARCHAR(30)  NOT NULL DEFAULT 'OPENDART',
    rcept_no           VARCHAR(20)  NOT NULL,
    report_name        TEXT,
    disclosed_at       DATE,
    source_url         TEXT,
    evidence_text      TEXT,
    evidence_location  TEXT,
    original_rcept_no  VARCHAR(20),
    correction_details JSONB,
    changed_values     JSONB,
    retrieved_at       TIMESTAMPTZ  NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_external_evidence_company FOREIGN KEY (company_id)
        REFERENCES company (company_id) ON DELETE RESTRICT,
    CONSTRAINT uq_external_evidence_source_rcept UNIQUE (source_system, rcept_no),
    CONSTRAINT ck_external_evidence_source CHECK (source_system IN ('OPENDART', 'ECOS', 'OTHER')),
    CONSTRAINT ck_external_evidence_rcept_no CHECK (
        source_system <> 'OPENDART' OR rcept_no ~ '^[0-9]{14}$'),
    CONSTRAINT ck_external_evidence_original_rcept_no CHECK (
        original_rcept_no IS NULL
        OR (original_rcept_no ~ '^[0-9]{14}$' AND original_rcept_no <> rcept_no))
);

CREATE INDEX ix_external_evidence_company_disclosed ON external_evidence (company_id, disclosed_at DESC);
CREATE INDEX ix_external_evidence_original_rcept ON external_evidence (original_rcept_no);

COMMENT ON TABLE external_evidence IS 'Selected external evidence used by an analysis. This table does not store all OpenDART disclosures.';

-- ---------------------------------------------------------
-- gap_result_evidence: many-to-many link between results and evidence
-- ---------------------------------------------------------
CREATE TABLE gap_result_evidence (
    result_id   BIGINT      NOT NULL,
    evidence_id BIGINT      NOT NULL,
    usage_type  VARCHAR(30) NOT NULL,
    reason      TEXT,

    CONSTRAINT pk_gap_result_evidence PRIMARY KEY (result_id, evidence_id),
    CONSTRAINT fk_gap_result_evidence_result FOREIGN KEY (result_id)
        REFERENCES gap_result (result_id) ON DELETE RESTRICT,
    CONSTRAINT fk_gap_result_evidence_evidence FOREIGN KEY (evidence_id)
        REFERENCES external_evidence (evidence_id) ON DELETE RESTRICT,
    CONSTRAINT ck_gap_result_evidence_usage_type CHECK (
        usage_type IN ('PRIMARY', 'SUPPORTING', 'CONTRADICTING'))
);

CREATE INDEX ix_gap_result_evidence_evidence ON gap_result_evidence (evidence_id);

COMMENT ON TABLE gap_result_evidence IS 'N:M mapping between gap results and selected external evidence.';
