-- =========================================================
-- Corporate Client Gap Agent - Mock CRM seed
-- 생성: build_seed.py (rm_plan_import.csv + PRD 9장 검증 케이스)
--
-- 1부 데모 데이터: rm_plan_import.csv 를 스키마 값으로 변환
--   EXPLICIT_NO -> EXPLICIT_NONE, UNDER_REVIEW -> REVIEW, FOREIGN_BUSINESS -> FX
--   consultation_date -> company.last_consulted_at, rm_memo -> note
--   OpenDART corp_cls 가 Y/K 가 아닌 기업(상장폐지·비상장) 제외
--   검증 케이스 기업(SK하이닉스)은 CSV 행 대신 2부 케이스로 대체
-- 2부 검증 케이스: 공시는 실제, CRM 기록은 가상. 기대 판정은 note 와 아래 주석 참고
-- =========================================================

BEGIN;

-- company
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00119195', '동화약품', '000020', '2026-01-12 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00112378', 'KR모터스', '000040', '2026-01-18 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00101628', '경방', '000050', '2026-01-20 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00126937', '삼양홀딩스', '000070', '2026-01-27 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00150244', '하이트진로', '000080', '2026-02-01 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00145109', '유한양행', '000100', '2026-02-04 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00113410', 'CJ대한통운', '000120', '2026-02-10 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00148993', '하이트진로홀딩스', '000140', '2026-02-13 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00117212', '두산', '000150', '2026-02-16 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00133335', '성창기업지주', '000180', '2026-02-19 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01516933', '덕양에너젠', '0001A0', '2026-02-22 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00109693', 'DL', '000210', '2026-02-25 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00144818', '유유제약', '000220', '2026-02-28 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00146083', '일동홀딩스', '000230', '2026-03-02 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00160047', '한국앤컴퍼니', '000240', '2026-03-05 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00128546', '삼천당제약', '000250', '2026-03-08 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00106641', '기아', '000270', '2026-03-11 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00126089', 'DH오토넥스', '000300', '2026-03-14 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00113508', '노루홀딩스', '000320', '2026-03-17 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00135917', '한화손해보험', '000370', '2026-03-23 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00129387', 'SP삼화', '000390', '2026-03-29 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00113562', '롯데손해보험', '000400', '2026-04-01 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00111847', '대원강업', '000430', '2026-04-07 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00149770', '중앙에너비스', '000440', '2026-04-10 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00148984', '시알홀딩스', '000480', '2026-04-16 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00109286', '대동', '000490', '2026-04-19 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00924931', '엔비알모션', '0004V0', '2026-04-22 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01884065', '디비금융제14호스팩', '0004Y0', '2026-04-25 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00104768', '가온전선', '000500', '2026-04-28 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00128032', '삼일제약', '000520', '2026-05-01 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00103176', '흥국화재', '000540', '2026-05-04 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00149026', 'CS홀딩스', '000590', '2026-05-07 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00116824', '동아쏘시오홀딩스', '000640', '2026-05-13 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00151395', '천일고속', '000650', '2026-05-16 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00164779', 'SK하이닉스', '000660', '2026-05-19 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00141307', '영풍', '000670', '2026-05-22 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00104698', 'LS네트웍스', '000680', '2026-05-25 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00163691', '유수홀딩스', '000700', '2026-05-28 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00164478', '현대건설', '000720', '2026-05-31 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00145686', '이화산업', '000760', '2026-06-03 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01829819', '아크릴', '0007C0', '2026-06-09 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01869710', '인벤테라', '0007J0', '2026-06-12 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00139214', '삼성화재해상보험', '000810', '2026-06-18 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00166519', '화천기공', '000850', '2026-06-24 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00100939', '강남제비스코', '000860', '2026-06-27 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00160588', '한화', '000880', '2026-06-30 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00123541', '보해양조', '000890', '2026-07-03 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01294110', '에스엔시스', '0008Z0', '2026-07-06 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00144252', '유니온', '000910', '2026-07-09 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00147222', '전방', '000950', '2026-07-12 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00159573', '한국주철관공업', '000970', '2026-07-15 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00160843', 'DB하이텍', '000990', '2026-07-18 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01781999', '에임드바이오', '0009K0', '2026-07-21 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00135999', '신라섬유', '001000', '2026-07-24 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00134723', '페이퍼코리아', '001020', '2026-07-27 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00148540', 'CJ', '001040', '2026-07-30 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00149947', 'JW중외제약', '001060', '2026-08-02 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00112970', '대한방직', '001070', '2026-08-05 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00120872', '만호제강', '001080', '2026-08-08 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00871587', '보원케미칼', '0010F0', '2026-08-11 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01867688', '와이즈플래닛컴퍼니', '0010S0', '2026-08-14 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00185301', '제이피아이헬스케어', '0010V0', '2026-08-17 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00120076', 'LX인터내셔널', '001120', '2026-08-20 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00113243', '대한제분', '001130', '2026-08-23 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01554508', '액스비스', '0011A0', '2026-09-04 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01279698', '채비', '0011T0', '2026-09-07 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00131054', '유진증권', '001200', '2026-09-10 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00106395', '금호전기', '001210', '2026-09-13 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00114792', '동국홀딩스', '001230', '2026-09-16 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00138190', 'GS글로벌', '001250', '2026-09-19 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00107066', '남광토건', '001260', '2026-09-22 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00123772', '부국증권', '001270', '2026-09-25 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00112059', '상상인증권', '001290', '2026-10-01 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00122472', 'PKC', '001340', '2026-10-04 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00126414', '삼성제약', '001360', '2026-10-05 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00152039', 'SG글로벌', '001380', '2026-10-06 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00101220', 'KG케미칼', '001390', '2026-10-06 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('01370322', '삼진식품', '0013V0', '2026-10-06 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00154055', '태원물산', '001420', '2026-10-07 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00106669', '세아베스틸지주', '001430', '2026-10-07 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00113207', '대한전선', '001440', '2026-10-07 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00102858', '고려아연', '010130', '2026-03-10 10:00+09');
INSERT INTO company (corp_code, corp_name, stock_code, last_consulted_at) VALUES ('00165413', '롯데케미칼', '011170', '2026-09-25 10:00+09');

-- 1부 데모 데이터
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산설비 투자 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-12 18:00+09', '생산라인 증설 가능성 검토 중' FROM company WHERE corp_code = '00119195';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-12 18:00+09', '생산라인 증설 가능성 검토 중' FROM company WHERE corp_code = '00119195';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-12 18:00+09', '생산라인 증설 가능성 검토 중' FROM company WHERE corp_code = '00119195';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규공장 투자 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-18 18:00+09', '공장 신설을 위한 자금조달 계획 있음' FROM company WHERE corp_code = '00112378';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-18 18:00+09', '공장 신설을 위한 자금조달 계획 있음' FROM company WHERE corp_code = '00112378';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-18 18:00+09', '공장 신설을 위한 자금조달 계획 있음' FROM company WHERE corp_code = '00112378';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-20 18:00+09', '미국 시장 진출 가능성 검토' FROM company WHERE corp_code = '00101628';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-20 18:00+09', '미국 시장 진출 가능성 검토' FROM company WHERE corp_code = '00101628';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외진출 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-20 18:00+09', '미국 시장 진출 가능성 검토' FROM company WHERE corp_code = '00101628';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산설비 투자 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-27 18:00+09', '자동차 부품 생산시설 확대 예정' FROM company WHERE corp_code = '00126937';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-27 18:00+09', '자동차 부품 생산시설 확대 예정' FROM company WHERE corp_code = '00126937';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-01-27 18:00+09', '자동차 부품 생산시설 확대 예정' FROM company WHERE corp_code = '00126937';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-01 18:00+09', '대규모 자금조달 가능성 있음' FROM company WHERE corp_code = '00150244';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-01 18:00+09', '대규모 자금조달 가능성 있음' FROM company WHERE corp_code = '00150244';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-01 18:00+09', '대규모 자금조달 가능성 있음' FROM company WHERE corp_code = '00150244';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규사업 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-04 18:00+09', '신규 사업 진출에 따른 자금 필요' FROM company WHERE corp_code = '00145109';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-04 18:00+09', '신규 사업 진출에 따른 자금 필요' FROM company WHERE corp_code = '00145109';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-04 18:00+09', '신규 사업 진출에 따른 자금 필요' FROM company WHERE corp_code = '00145109';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-10 18:00+09', '현재 자금수요 특별히 없음' FROM company WHERE corp_code = '00113410';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-10 18:00+09', '현재 자금수요 특별히 없음' FROM company WHERE corp_code = '00113410';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-10 18:00+09', '현재 자금수요 특별히 없음' FROM company WHERE corp_code = '00113410';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '공장 증설 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-13 18:00+09', '해외 매출 증가 예상' FROM company WHERE corp_code = '00148993';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-13 18:00+09', '해외 매출 증가 예상' FROM company WHERE corp_code = '00148993';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-13 18:00+09', '해외 매출 증가 예상' FROM company WHERE corp_code = '00148993';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-16 18:00+09', '운전자금 확보 필요' FROM company WHERE corp_code = '00117212';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-16 18:00+09', '운전자금 확보 필요' FROM company WHERE corp_code = '00117212';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-16 18:00+09', '운전자금 확보 필요' FROM company WHERE corp_code = '00117212';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '설비교체 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-19 18:00+09', '노후 설비 교체 계획' FROM company WHERE corp_code = '00133335';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-19 18:00+09', '노후 설비 교체 계획' FROM company WHERE corp_code = '00133335';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-19 18:00+09', '노후 설비 교체 계획' FROM company WHERE corp_code = '00133335';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-22 18:00+09', '동남아 시장 진출 가능성 검토' FROM company WHERE corp_code = '01516933';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-22 18:00+09', '동남아 시장 진출 가능성 검토' FROM company WHERE corp_code = '01516933';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외법인 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-22 18:00+09', '동남아 시장 진출 가능성 검토' FROM company WHERE corp_code = '01516933';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산라인 증설', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-25 18:00+09', '생산량 확대를 위한 투자 및 차입 계획' FROM company WHERE corp_code = '00109693';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-25 18:00+09', '생산량 확대를 위한 투자 및 차입 계획' FROM company WHERE corp_code = '00109693';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-25 18:00+09', '생산량 확대를 위한 투자 및 차입 계획' FROM company WHERE corp_code = '00109693';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-28 18:00+09', '사업 안정화에 집중' FROM company WHERE corp_code = '00144818';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-28 18:00+09', '사업 안정화에 집중' FROM company WHERE corp_code = '00144818';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-02-28 18:00+09', '사업 안정화에 집중' FROM company WHERE corp_code = '00144818';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규 연구소 설립', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-02 18:00+09', 'R&D 투자 확대 계획' FROM company WHERE corp_code = '00146083';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-02 18:00+09', 'R&D 투자 확대 계획' FROM company WHERE corp_code = '00146083';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-02 18:00+09', 'R&D 투자 확대 계획' FROM company WHERE corp_code = '00146083';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-05 18:00+09', '해외 매출 증가에 대비한 자금 확보' FROM company WHERE corp_code = '00160047';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-05 18:00+09', '해외 매출 증가에 대비한 자금 확보' FROM company WHERE corp_code = '00160047';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-05 18:00+09', '해외 매출 증가에 대비한 자금 확보' FROM company WHERE corp_code = '00160047';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '공장 이전 계획', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-08 18:00+09', '생산시설 이전에 자금 필요' FROM company WHERE corp_code = '00128546';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-08 18:00+09', '생산시설 이전에 자금 필요' FROM company WHERE corp_code = '00128546';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-08 18:00+09', '생산시설 이전에 자금 필요' FROM company WHERE corp_code = '00128546';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신약 연구 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-11 18:00+09', '연구개발 투자 지속 예정' FROM company WHERE corp_code = '00106641';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-11 18:00+09', '연구개발 투자 지속 예정' FROM company WHERE corp_code = '00106641';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외진출 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-11 18:00+09', '연구개발 투자 지속 예정' FROM company WHERE corp_code = '00106641';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-14 18:00+09', '신규 투자계획 없음' FROM company WHERE corp_code = '00126089';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-14 18:00+09', '신규 투자계획 없음' FROM company WHERE corp_code = '00126089';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-14 18:00+09', '신규 투자계획 없음' FROM company WHERE corp_code = '00126089';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산설비 투자 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-17 18:00+09', '생산 증가에 따른 운전자금 필요' FROM company WHERE corp_code = '00113508';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 필요', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-17 18:00+09', '생산 증가에 따른 운전자금 필요' FROM company WHERE corp_code = '00113508';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-17 18:00+09', '생산 증가에 따른 운전자금 필요' FROM company WHERE corp_code = '00113508';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규 프로젝트 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-23 18:00+09', '신규 개발사업 자금 검토' FROM company WHERE corp_code = '00135917';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '프로젝트파이낸싱 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-23 18:00+09', '신규 개발사업 자금 검토' FROM company WHERE corp_code = '00135917';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-23 18:00+09', '신규 개발사업 자금 검토' FROM company WHERE corp_code = '00135917';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '공장 증설', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-29 18:00+09', '수출 물량 증가에 따른 생산 확대' FROM company WHERE corp_code = '00129387';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-29 18:00+09', '수출 물량 증가에 따른 생산 확대' FROM company WHERE corp_code = '00129387';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-03-29 18:00+09', '수출 물량 증가에 따른 생산 확대' FROM company WHERE corp_code = '00129387';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-01 18:00+09', '원재료 가격 상승으로 자금 필요' FROM company WHERE corp_code = '00113562';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-01 18:00+09', '원재료 가격 상승으로 자금 필요' FROM company WHERE corp_code = '00113562';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-01 18:00+09', '원재료 가격 상승으로 자금 필요' FROM company WHERE corp_code = '00113562';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-07 18:00+09', '해외 건설 프로젝트 참여 검토' FROM company WHERE corp_code = '00111847';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-07 18:00+09', '해외 건설 프로젝트 참여 검토' FROM company WHERE corp_code = '00111847';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-07 18:00+09', '해외 건설 프로젝트 참여 검토' FROM company WHERE corp_code = '00111847';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '전기차 부품 설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-10 18:00+09', '전기차 부품 생산 확대' FROM company WHERE corp_code = '00149770';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-10 18:00+09', '전기차 부품 생산 확대' FROM company WHERE corp_code = '00149770';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-10 18:00+09', '전기차 부품 생산 확대' FROM company WHERE corp_code = '00149770';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규공장 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-16 18:00+09', '해외 생산거점 확보 검토' FROM company WHERE corp_code = '00148984';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-16 18:00+09', '해외 생산거점 확보 검토' FROM company WHERE corp_code = '00148984';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-16 18:00+09', '해외 생산거점 확보 검토' FROM company WHERE corp_code = '00148984';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '연구개발 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-19 18:00+09', '신규 제품 개발 추진' FROM company WHERE corp_code = '00109286';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-19 18:00+09', '신규 제품 개발 추진' FROM company WHERE corp_code = '00109286';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-19 18:00+09', '신규 제품 개발 추진' FROM company WHERE corp_code = '00109286';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-22 18:00+09', '해외 임상시험 자금 검토' FROM company WHERE corp_code = '00924931';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-22 18:00+09', '해외 임상시험 자금 검토' FROM company WHERE corp_code = '00924931';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외진출 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-22 18:00+09', '해외 임상시험 자금 검토' FROM company WHERE corp_code = '00924931';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산설비 교체', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-25 18:00+09', '노후 생산설비 교체 예정' FROM company WHERE corp_code = '01884065';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-25 18:00+09', '노후 생산설비 교체 예정' FROM company WHERE corp_code = '01884065';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-25 18:00+09', '노후 생산설비 교체 예정' FROM company WHERE corp_code = '01884065';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-28 18:00+09', '해외 거래처 확대 추진' FROM company WHERE corp_code = '00104768';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-28 18:00+09', '해외 거래처 확대 추진' FROM company WHERE corp_code = '00104768';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-04-28 18:00+09', '해외 거래처 확대 추진' FROM company WHERE corp_code = '00104768';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '공장 증설', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-01 18:00+09', '생산능력 확대 필요' FROM company WHERE corp_code = '00128032';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-01 18:00+09', '생산능력 확대 필요' FROM company WHERE corp_code = '00128032';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-01 18:00+09', '생산능력 확대 필요' FROM company WHERE corp_code = '00128032';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규 생산라인 구축', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-04 18:00+09', '신규 생산라인을 통한 수출 확대 계획' FROM company WHERE corp_code = '00103176';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-04 18:00+09', '신규 생산라인을 통한 수출 확대 계획' FROM company WHERE corp_code = '00103176';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-04 18:00+09', '신규 생산라인을 통한 수출 확대 계획' FROM company WHERE corp_code = '00103176';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-07 18:00+09', '매출 증가에 따른 운전자금 필요' FROM company WHERE corp_code = '00149026';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 필요', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-07 18:00+09', '매출 증가에 따른 운전자금 필요' FROM company WHERE corp_code = '00149026';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-07 18:00+09', '매출 증가에 따른 운전자금 필요' FROM company WHERE corp_code = '00149026';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-13 18:00+09', '장기 투자자금 조달 예정' FROM company WHERE corp_code = '00116824';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-13 18:00+09', '장기 투자자금 조달 예정' FROM company WHERE corp_code = '00116824';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-13 18:00+09', '장기 투자자금 조달 예정' FROM company WHERE corp_code = '00116824';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '설비 투자 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-16 18:00+09', '설비 효율 개선 검토' FROM company WHERE corp_code = '00151395';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-16 18:00+09', '설비 효율 개선 검토' FROM company WHERE corp_code = '00151395';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-16 18:00+09', '설비 효율 개선 검토' FROM company WHERE corp_code = '00151395';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '친환경 설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-22 18:00+09', '친환경 제품 해외 판매 확대' FROM company WHERE corp_code = '00141307';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-22 18:00+09', '친환경 제품 해외 판매 확대' FROM company WHERE corp_code = '00141307';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-22 18:00+09', '친환경 제품 해외 판매 확대' FROM company WHERE corp_code = '00141307';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-25 18:00+09', '현재 특별한 자금수요 없음' FROM company WHERE corp_code = '00104698';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-25 18:00+09', '현재 특별한 자금수요 없음' FROM company WHERE corp_code = '00104698';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-25 18:00+09', '현재 특별한 자금수요 없음' FROM company WHERE corp_code = '00104698';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '자동화 설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-28 18:00+09', '스마트공장 전환 추진' FROM company WHERE corp_code = '00163691';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-28 18:00+09', '스마트공장 전환 추진' FROM company WHERE corp_code = '00163691';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-28 18:00+09', '스마트공장 전환 추진' FROM company WHERE corp_code = '00163691';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신약개발 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-31 18:00+09', '연구개발 및 해외시장 진출 자금 필요' FROM company WHERE corp_code = '00164478';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-31 18:00+09', '연구개발 및 해외시장 진출 자금 필요' FROM company WHERE corp_code = '00164478';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외진출 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-05-31 18:00+09', '연구개발 및 해외시장 진출 자금 필요' FROM company WHERE corp_code = '00164478';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-03 18:00+09', '수출 증가로 운전자금 필요' FROM company WHERE corp_code = '00145686';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-03 18:00+09', '수출 증가로 운전자금 필요' FROM company WHERE corp_code = '00145686';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-03 18:00+09', '수출 증가로 운전자금 필요' FROM company WHERE corp_code = '00145686';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '공장 이전', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-09 18:00+09', '공장 이전 비용 조달 필요' FROM company WHERE corp_code = '01829819';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-09 18:00+09', '공장 이전 비용 조달 필요' FROM company WHERE corp_code = '01829819';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-09 18:00+09', '공장 이전 비용 조달 필요' FROM company WHERE corp_code = '01829819';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-12 18:00+09', '동남아 시장 진출 가능성' FROM company WHERE corp_code = '01869710';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-12 18:00+09', '동남아 시장 진출 가능성' FROM company WHERE corp_code = '01869710';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외법인 설립 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-12 18:00+09', '동남아 시장 진출 가능성' FROM company WHERE corp_code = '01869710';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '전기차 설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-18 18:00+09', '전기차 부품 수출 확대' FROM company WHERE corp_code = '00139214';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-18 18:00+09', '전기차 부품 수출 확대' FROM company WHERE corp_code = '00139214';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-18 18:00+09', '전기차 부품 수출 확대' FROM company WHERE corp_code = '00139214';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '공장 증설', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-24 18:00+09', '식품 수출 증가 대응' FROM company WHERE corp_code = '00166519';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-24 18:00+09', '식품 수출 증가 대응' FROM company WHERE corp_code = '00166519';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-24 18:00+09', '식품 수출 증가 대응' FROM company WHERE corp_code = '00166519';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-27 18:00+09', '사업 안정화 계획' FROM company WHERE corp_code = '00100939';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-27 18:00+09', '사업 안정화 계획' FROM company WHERE corp_code = '00100939';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-27 18:00+09', '사업 안정화 계획' FROM company WHERE corp_code = '00100939';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '설비 교체', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-30 18:00+09', '생산설비 교체 및 운전자금 확보' FROM company WHERE corp_code = '00160588';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 필요', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-30 18:00+09', '생산설비 교체 및 운전자금 확보' FROM company WHERE corp_code = '00160588';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-06-30 18:00+09', '생산설비 교체 및 운전자금 확보' FROM company WHERE corp_code = '00160588';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규공장 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-03 18:00+09', '국내외 생산시설 확대 검토' FROM company WHERE corp_code = '00123541';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-03 18:00+09', '국내외 생산시설 확대 검토' FROM company WHERE corp_code = '00123541';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-03 18:00+09', '국내외 생산시설 확대 검토' FROM company WHERE corp_code = '00123541';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '연구개발 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-06 18:00+09', '해외 임상 및 연구개발 추진' FROM company WHERE corp_code = '01294110';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-06 18:00+09', '해외 임상 및 연구개발 추진' FROM company WHERE corp_code = '01294110';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외진출 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-06 18:00+09', '해외 임상 및 연구개발 추진' FROM company WHERE corp_code = '01294110';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-09 18:00+09', '장기 운영자금 확보 검토' FROM company WHERE corp_code = '00144252';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-09 18:00+09', '장기 운영자금 확보 검토' FROM company WHERE corp_code = '00144252';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-09 18:00+09', '장기 운영자금 확보 검토' FROM company WHERE corp_code = '00144252';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-12 18:00+09', '수출 주문 증가에 대응' FROM company WHERE corp_code = '00147222';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-12 18:00+09', '수출 주문 증가에 대응' FROM company WHERE corp_code = '00147222';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-12 18:00+09', '수출 주문 증가에 대응' FROM company WHERE corp_code = '00147222';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '자동화 설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-15 18:00+09', '생산성 향상을 위한 자동화' FROM company WHERE corp_code = '00159573';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-15 18:00+09', '생산성 향상을 위한 자동화' FROM company WHERE corp_code = '00159573';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-15 18:00+09', '생산성 향상을 위한 자동화' FROM company WHERE corp_code = '00159573';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '친환경 설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-18 18:00+09', '친환경 제품 해외 진출' FROM company WHERE corp_code = '00160843';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-18 18:00+09', '친환경 제품 해외 진출' FROM company WHERE corp_code = '00160843';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-18 18:00+09', '친환경 제품 해외 진출' FROM company WHERE corp_code = '00160843';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-21 18:00+09', '프로젝트 자금 필요 가능성' FROM company WHERE corp_code = '01781999';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-21 18:00+09', '프로젝트 자금 필요 가능성' FROM company WHERE corp_code = '01781999';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-21 18:00+09', '프로젝트 자금 필요 가능성' FROM company WHERE corp_code = '01781999';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신약 연구 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-24 18:00+09', '신약개발 자금 확보 필요' FROM company WHERE corp_code = '00135999';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-24 18:00+09', '신약개발 자금 확보 필요' FROM company WHERE corp_code = '00135999';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외진출 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-24 18:00+09', '신약개발 자금 확보 필요' FROM company WHERE corp_code = '00135999';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-27 18:00+09', '해외 거래처 신규 확보' FROM company WHERE corp_code = '00134723';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-27 18:00+09', '해외 거래처 신규 확보' FROM company WHERE corp_code = '00134723';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-27 18:00+09', '해외 거래처 신규 확보' FROM company WHERE corp_code = '00134723';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '공장 증설', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-30 18:00+09', '생산능력 확대 추진' FROM company WHERE corp_code = '00148540';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-30 18:00+09', '생산능력 확대 추진' FROM company WHERE corp_code = '00148540';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-07-30 18:00+09', '생산능력 확대 추진' FROM company WHERE corp_code = '00148540';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '설비 교체', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-02 18:00+09', '생산설비 노후화 대응' FROM company WHERE corp_code = '00149947';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-02 18:00+09', '생산설비 노후화 대응' FROM company WHERE corp_code = '00149947';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-02 18:00+09', '생산설비 노후화 대응' FROM company WHERE corp_code = '00149947';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-05 18:00+09', '수출 증가로 운영자금 필요' FROM company WHERE corp_code = '00112970';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 필요', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-05 18:00+09', '수출 증가로 운영자금 필요' FROM company WHERE corp_code = '00112970';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-05 18:00+09', '수출 증가로 운영자금 필요' FROM company WHERE corp_code = '00112970';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규 연구소 설립', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-08 18:00+09', 'R&D와 해외사업 동시 추진' FROM company WHERE corp_code = '00120872';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-08 18:00+09', 'R&D와 해외사업 동시 추진' FROM company WHERE corp_code = '00120872';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외진출 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-08 18:00+09', 'R&D와 해외사업 동시 추진' FROM company WHERE corp_code = '00120872';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산라인 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-11 18:00+09', '생산시설 및 수출 확대' FROM company WHERE corp_code = '00871587';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-11 18:00+09', '생산시설 및 수출 확대' FROM company WHERE corp_code = '00871587';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-11 18:00+09', '생산시설 및 수출 확대' FROM company WHERE corp_code = '00871587';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-14 18:00+09', '해외법인 설립에 따른 자금 검토' FROM company WHERE corp_code = '01867688';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-14 18:00+09', '해외법인 설립에 따른 자금 검토' FROM company WHERE corp_code = '01867688';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-14 18:00+09', '해외법인 설립에 따른 자금 검토' FROM company WHERE corp_code = '01867688';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '자동화 설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-17 18:00+09', '스마트공장 전환 계획' FROM company WHERE corp_code = '00185301';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-17 18:00+09', '스마트공장 전환 계획' FROM company WHERE corp_code = '00185301';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-17 18:00+09', '스마트공장 전환 계획' FROM company WHERE corp_code = '00185301';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규사업 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-20 18:00+09', '신규 개발사업 및 해외사업 검토' FROM company WHERE corp_code = '00120076';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-20 18:00+09', '신규 개발사업 및 해외사업 검토' FROM company WHERE corp_code = '00120076';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-20 18:00+09', '신규 개발사업 및 해외사업 검토' FROM company WHERE corp_code = '00120076';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-23 18:00+09', '현재 신규 사업계획 없음' FROM company WHERE corp_code = '00113243';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-23 18:00+09', '현재 신규 사업계획 없음' FROM company WHERE corp_code = '00113243';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-08-23 18:00+09', '현재 신규 사업계획 없음' FROM company WHERE corp_code = '00113243';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-04 18:00+09', '동남아 사업 진출 검토' FROM company WHERE corp_code = '01554508';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-04 18:00+09', '동남아 사업 진출 검토' FROM company WHERE corp_code = '01554508';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-04 18:00+09', '동남아 사업 진출 검토' FROM company WHERE corp_code = '01554508';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규 생산라인', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-07 18:00+09', '수출 증가에 따른 생산시설 투자' FROM company WHERE corp_code = '01279698';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-07 18:00+09', '수출 증가에 따른 생산시설 투자' FROM company WHERE corp_code = '01279698';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-07 18:00+09', '수출 증가에 따른 생산시설 투자' FROM company WHERE corp_code = '01279698';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-10 18:00+09', '원자재 가격 상승 대응' FROM company WHERE corp_code = '00131054';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 필요', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-10 18:00+09', '원자재 가격 상승 대응' FROM company WHERE corp_code = '00131054';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-10 18:00+09', '원자재 가격 상승 대응' FROM company WHERE corp_code = '00131054';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규 프로젝트 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-13 18:00+09', '신규 개발사업 추진' FROM company WHERE corp_code = '00106395';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '프로젝트파이낸싱 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-13 18:00+09', '신규 개발사업 추진' FROM company WHERE corp_code = '00106395';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-13 18:00+09', '신규 개발사업 추진' FROM company WHERE corp_code = '00106395';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신약 연구 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-16 18:00+09', '해외 임상시험 확대' FROM company WHERE corp_code = '00114792';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-16 18:00+09', '해외 임상시험 확대' FROM company WHERE corp_code = '00114792';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외진출 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-16 18:00+09', '해외 임상시험 확대' FROM company WHERE corp_code = '00114792';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-19 18:00+09', '생산량과 수출 확대 계획' FROM company WHERE corp_code = '00138190';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-19 18:00+09', '생산량과 수출 확대 계획' FROM company WHERE corp_code = '00138190';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-19 18:00+09', '생산량과 수출 확대 계획' FROM company WHERE corp_code = '00138190';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-22 18:00+09', '장기 운영자금 조달' FROM company WHERE corp_code = '00107066';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-22 18:00+09', '장기 운영자금 조달' FROM company WHERE corp_code = '00107066';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-22 18:00+09', '장기 운영자금 조달' FROM company WHERE corp_code = '00107066';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '자동화 설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-25 18:00+09', '스마트공장과 수출 확대 추진' FROM company WHERE corp_code = '00123772';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-25 18:00+09', '스마트공장과 수출 확대 추진' FROM company WHERE corp_code = '00123772';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-09-25 18:00+09', '스마트공장과 수출 확대 추진' FROM company WHERE corp_code = '00123772';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '공장 이전', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-01 18:00+09', '생산거점 재편 및 해외사업 확대' FROM company WHERE corp_code = '00112059';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-01 18:00+09', '생산거점 재편 및 해외사업 확대' FROM company WHERE corp_code = '00112059';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-01 18:00+09', '생산거점 재편 및 해외사업 확대' FROM company WHERE corp_code = '00112059';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산라인 증설', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-04 18:00+09', '생산 및 수출 확대를 위한 투자' FROM company WHERE corp_code = '00122472';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-04 18:00+09', '생산 및 수출 확대를 위한 투자' FROM company WHERE corp_code = '00122472';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-04 18:00+09', '생산 및 수출 확대를 위한 투자' FROM company WHERE corp_code = '00122472';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-05 18:00+09', '매출 증가에 따른 운전자금 필요' FROM company WHERE corp_code = '00126414';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 필요', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-05 18:00+09', '매출 증가에 따른 운전자금 필요' FROM company WHERE corp_code = '00126414';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-05 18:00+09', '매출 증가에 따른 운전자금 필요' FROM company WHERE corp_code = '00126414';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '설비 교체', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-06 18:00+09', '노후 설비 교체와 수출 확대' FROM company WHERE corp_code = '00152039';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-06 18:00+09', '노후 설비 교체와 수출 확대' FROM company WHERE corp_code = '00152039';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-06 18:00+09', '노후 설비 교체와 수출 확대' FROM company WHERE corp_code = '00152039';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '신규 연구시설', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-06 18:00+09', '연구시설 투자 및 해외시장 진출' FROM company WHERE corp_code = '00101220';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '회사채 발행 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-06 18:00+09', '연구시설 투자 및 해외시장 진출' FROM company WHERE corp_code = '00101220';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외진출 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-06 18:00+09', '연구시설 투자 및 해외시장 진출' FROM company WHERE corp_code = '00101220';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-06 18:00+09', '현재 대규모 투자계획 없음' FROM company WHERE corp_code = '01370322';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-06 18:00+09', '현재 대규모 투자계획 없음' FROM company WHERE corp_code = '01370322';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-06 18:00+09', '현재 대규모 투자계획 없음' FROM company WHERE corp_code = '01370322';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '생산설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-07 18:00+09', '생산시설 및 해외사업 확대' FROM company WHERE corp_code = '00154055';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-07 18:00+09', '생산시설 및 해외사업 확대' FROM company WHERE corp_code = '00154055';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-07 18:00+09', '생산시설 및 해외사업 확대' FROM company WHERE corp_code = '00154055';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', '자동화 설비 투자', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-07 18:00+09', '자동화 및 수출 확대 추진' FROM company WHERE corp_code = '00106669';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-07 18:00+09', '자동화 및 수출 확대 추진' FROM company WHERE corp_code = '00106669';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '수출 확대', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-07 18:00+09', '자동화 및 수출 확대 추진' FROM company WHERE corp_code = '00106669';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'INVESTMENT', NULL, 'EXPLICIT_NONE', 'NOT_APPLICABLE', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-07 18:00+09', '해외사업 진출 가능성 검토' FROM company WHERE corp_code = '00113207';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FUNDING', '운전자금 차입 예정', 'EXPLICIT_YES', 'PLANNED', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-07 18:00+09', '해외사업 진출 가능성 검토' FROM company WHERE corp_code = '00113207';
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, source, evidence_level, validity_status, recorded_at, note) SELECT company_id, 'FX', '해외사업 검토', 'EXPLICIT_YES', 'REVIEW', '가상 RM 상담', 'NONE', 'UNVERIFIED', '2026-10-07 18:00+09', '해외사업 진출 가능성 검토' FROM company WHERE corp_code = '00113207';

-- 2부 검증 케이스 (PRD 9장)
-- C01 기대: 상충 / 우선 확인 1. 근거 20260225801974 신규시설투자 용인 1기 Fab Phase 2~6, 21조 6,081억
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'INVESTMENT', '2026년 신규 Fab 투자', 'EXPLICIT_NONE', 'NOT_APPLICABLE', '2026-01-15 10:00+09', NULL, NULL, NULL, NULL, '가상 RM 상담 (검증 C01)', 'DIRECT', NULL, 'UNVERIFIED', '2026년 신규 Fab 투자 계획 없다고 확인' FROM company WHERE corp_code = '00164779';
-- C02 기대: 상충(일정) / 우선 확인 1. 근거 20251203800001 정정: 출자기간 2025-12-31 -> 2030-12-01
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'FX', '중국 우시 법인(SK hynix Semiconductor (China)) 출자', 'EXPLICIT_YES', 'IN_PROGRESS', '2025-11-10 10:00+09', 2394000000000, 'KRW', '2025-12-31', 'DAY', '가상 RM 상담 (검증 C02)', 'DIRECT', NULL, 'UNVERIFIED', '우시 생산시설 보완 출자, 2025년 말까지 분할 출자 완료 예정' FROM company WHERE corp_code = '00164779';
-- C03 기대: 신규 정보 / 다음 확인 2. 근거 20260624000420 유상증자(ADR) -> 정정 20260706000403, 20260710000008 최신 버전(시설자금 40조 230억) 적용
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'FUNDING', NULL, 'UNCONFIRMED', 'UNKNOWN', NULL, NULL, NULL, NULL, NULL, '가상 RM 상담 (검증 C03)', NULL, NULL, 'UNVERIFIED', '자금조달 계획은 상담에서 확인하지 못함' FROM company WHERE corp_code = '00164779';
-- C04 기대: 구체화 / 세부 갱신 3. 근거 20251215801451 장래사업계획 USD 7,432백만, 2025-12-15~2029-12-31
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'FX', '미국 내 제련소 진출', 'EXPLICIT_YES', 'REVIEW', '2025-11-20 10:00+09', NULL, NULL, NULL, NULL, '가상 RM 상담 (검증 C04)', 'DIRECT', NULL, 'UNVERIFIED', '미국 제련소 진출 검토 중, 규모·시기 미정' FROM company WHERE corp_code = '00102858';
-- C05 기대: 취소 / 우선 확인 1. 근거 20260917800509 정정: 투자 중단, 집행액 166억, 종료일 2026-09-17
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'INVESTMENT', '울산공장 폐PET 화학적 재활용 시설', 'EXPLICIT_YES', 'IN_PROGRESS', '2026-03-20 10:00+09', 77000000000, 'KRW', '2027-12-31', 'DAY', '가상 RM 상담 (검증 C05)', 'DIRECT', NULL, 'UNVERIFIED', '폐PET 재활용 시설 투자 진행 중' FROM company WHERE corp_code = '00165413';
-- C06 기대: 완료 / 다음 확인 2. 근거 20260630801556 정정: 투자완료, 최종 995억(+11.5%, 주요 변경 기준 미만)
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'INVESTMENT', '온산제련소 퓨머 설비 개조', 'EXPLICIT_YES', 'IN_PROGRESS', '2026-03-10 10:00+09', 89200000000, 'KRW', '2026-06-30', 'DAY', '가상 RM 상담 (검증 C06)', 'DIRECT', NULL, 'UNVERIFIED', '퓨머 1기 리사이클링 동 제련 설비 개조 진행 중' FROM company WHERE corp_code = '00102858';
-- C07 기대: Gap 없음(일치). 확인일 이후 관련 공시 없음. 근거 공시 20260917800656 는 확인일 이전
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'INVESTMENT', '에이치앤엘어드밴스드 지분 출자', 'EXPLICIT_YES', 'PLANNED', '2026-09-25 10:00+09', 600000000000, 'KRW', '2026-09-28', 'DAY', '가상 RM 상담 (검증 C07)', 'DIRECT', NULL, 'UNVERIFIED', '대산공장 사업재편 후속 출자 6,000억, 9/28 취득 예정' FROM company WHERE corp_code = '00165413';
-- C08 기대: Gap 없음(무관한 공시) + 유효기간 만료 재확인. 20260917800656 은 국내 법인 출자라 매칭 안 됨
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'FX', '해외 신규 법인 설립·출자', 'EXPLICIT_NONE', 'NOT_APPLICABLE', '2026-03-20 10:00+09', NULL, NULL, NULL, NULL, '가상 RM 상담 (검증 C08)', 'DIRECT', '2026-06-30', 'UNVERIFIED', '해외 신규 법인 계획 없음. 고객이 2026년 상반기까지 유효하다고 언급' FROM company WHERE corp_code = '00165413';
-- C09 기대: Gap 없음(중복공시). 20260303801364 정정은 산정방식 기재만 추가
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'FX', '미국 NAND 법인(SK hynix NAND Product Solutions) 출자', 'EXPLICIT_YES', 'PLANNED', '2026-02-20 10:00+09', 14428000000000, 'KRW', '2030-01-28', 'DAY', '가상 RM 상담 (검증 C09)', 'DOCUMENT', NULL, 'UNVERIFIED', '미국 자회사 출자 14조 4,280억 확인' FROM company WHERE corp_code = '00164779';
-- C10 기대: 추가 확인 필요(재무 신호만). 총차입금 증가율 20% 이상 여부 미검증 - 데이터 확인 필요
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'FUNDING', '추가 차입', 'EXPLICIT_NONE', 'NOT_APPLICABLE', '2026-03-20 10:00+09', NULL, NULL, NULL, NULL, '가상 RM 상담 (검증 C10)', 'DIRECT', NULL, 'UNVERIFIED', '추가 차입 계획 없음' FROM company WHERE corp_code = '00165413';
-- C11 기대: 추가 확인 필요(매칭 불명확). 20260807800613, 20260807800602 신규시설투자 대상 명시 없음
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'INVESTMENT', '용인 2기 Fab 투자', 'EXPLICIT_YES', 'REVIEW', '2026-05-19 10:00+09', NULL, NULL, NULL, NULL, '가상 RM 상담 (검증 C11)', 'DIRECT', NULL, 'UNVERIFIED', '용인 2기 Fab 투자 검토 중' FROM company WHERE corp_code = '00164779';
-- C12 기대: 추가 확인 필요(선후 불명확). 20251215000398 유상증자 결정과 같은 날
INSERT INTO rm_plan (company_id, domain, scope, knowledge_status, plan_status, last_confirmed_at, amount, currency, expected_at, expected_precision, source, evidence_level, valid_until, validity_status, note) SELECT company_id, 'FUNDING', '추가 유상증자', 'EXPLICIT_NONE', 'NOT_APPLICABLE', '2025-12-15 00:00+09', NULL, NULL, NULL, NULL, '가상 RM 상담 (검증 C12)', 'DIRECT', NULL, 'UNVERIFIED', '추가 증자 계획 없음. 확인 시각 미기록(날짜만)' FROM company WHERE corp_code = '00102858';

COMMIT;

-- 제외한 비상장·상장폐지 기업 (corp_code, 이름, corp_cls)
--   00149293 신한은행 E
--   00254045 우리은행 E
--   00117744 메리츠화재해상보험 E
--   00148504 한국스탠다드차타드은행 E
--   00129411 삼환기업 E
--   00110963 대아건설 E
--   00120377 로케트전기 E
--   00104971 그린손해보험 E
--   00148744 제일화재해상보험 E
--   00134060 씨앤상선 E
--   00101257 경남기업 E
--   00126229 삼성물산 E
--   00104519 국보 E
--   00131434 서통 E
--   00112068 마이크로닉스 E
--   00163178 우리증권 E
--   00148328 제일모직 E
--   00155498 풍림산업 E
--   00152914 FnC코오롱 E