CREATE TABLE IF NOT EXISTS company (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_code VARCHAR(8) NOT NULL UNIQUE,
    corp_name VARCHAR(200) NOT NULL,
    stock_code VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    consultation_date DATE,
    rm_memo TEXT,
    CONSTRAINT ck_company_corp_code CHECK (corp_code ~ '^[0-9]{8}$')
);

ALTER TABLE company
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS rm_plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(company_id) ON DELETE RESTRICT,
    source_plan_key VARCHAR(128) NOT NULL,
    domain VARCHAR(30) NOT NULL,
    scope TEXT,
    knowledge_status VARCHAR(30) NOT NULL,
    plan_status VARCHAR(30) NOT NULL,
    last_confirmed_at TIMESTAMPTZ,
    amount NUMERIC(20, 2),
    currency VARCHAR(3),
    expected_at DATE,
    expected_at_label VARCHAR(128),
    expected_at_precision VARCHAR(20),
    source TEXT,
    evidence_level VARCHAR(30) NOT NULL,
    source_reference TEXT,
    valid_until DATE,
    review_due_at DATE,
    validity_status VARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED',
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT,
    CONSTRAINT uq_rm_plan_source_key UNIQUE (company_id, source_plan_key),
    CONSTRAINT ck_rm_plan_domain CHECK (domain IN ('INVESTMENT', 'FUNDING', 'FX')),
    CONSTRAINT ck_rm_plan_knowledge_status CHECK (
        knowledge_status IN ('EXPLICIT_YES', 'EXPLICIT_NONE', 'UNCONFIRMED', 'UNRECORDED')),
    CONSTRAINT ck_rm_plan_status CHECK (
        plan_status IN ('REVIEW', 'PLANNED', 'IN_PROGRESS', 'COMPLETED',
                        'CANCELED', 'NOT_APPLICABLE', 'UNKNOWN')),
    CONSTRAINT ck_rm_plan_evidence_level CHECK (
        evidence_level IN ('DIRECT', 'DOCUMENT', 'INDIRECT', 'NONE')),
    CONSTRAINT ck_rm_plan_validity_status CHECK (
        validity_status IN ('UNVERIFIED', 'NO_CHANGE_EVIDENCE', 'RECHECK_NEEDED', 'PENDING'))
);

CREATE TABLE IF NOT EXISTS gap_analysis (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(company_id) ON DELETE RESTRICT,
    analysis_at TIMESTAMPTZ NOT NULL,
    query_start_at TIMESTAMPTZ,
    query_end_at TIMESTAMPTZ,
    retrieval_status VARCHAR(30) NOT NULL,
    crm_snapshot JSONB NOT NULL,
    rule_version VARCHAR(30) NOT NULL,
    collection_messages JSONB NOT NULL DEFAULT '[]'::jsonb,
    company_status VARCHAR(30) NOT NULL,
    disclosure_status VARCHAR(30) NOT NULL,
    financial_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_gap_analysis_retrieval_status CHECK (
        retrieval_status IN ('SUCCESS', 'PARTIAL_FAILURE', 'FAILURE'))
);

CREATE TABLE IF NOT EXISTS gap_result (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id BIGINT NOT NULL REFERENCES gap_analysis(analysis_id) ON DELETE CASCADE,
    plan_id BIGINT REFERENCES rm_plan(plan_id) ON DELETE RESTRICT,
    domain VARCHAR(30) NOT NULL,
    change_type VARCHAR(30),
    assessment_status VARCHAR(30) NOT NULL,
    priority SMALLINT,
    priority_reason TEXT,
    changed_fields JSONB,
    financial_signals JSONB,
    questions JSONB,
    environment_context JSONB,
    status_summary TEXT,
    compared_from DATE,
    CONSTRAINT ck_gap_result_domain CHECK (domain IN ('INVESTMENT', 'FUNDING', 'FX')),
    CONSTRAINT ck_gap_result_change_type CHECK (
        change_type IS NULL OR change_type IN (
            'CONFLICT', 'NEW_INFO', 'SPECIFIED', 'CANCELED_OR_COMPLETED', 'NEEDS_CONFIRMATION')),
    CONSTRAINT ck_gap_result_assessment_status CHECK (
        assessment_status IN ('CONFIRMED', 'PENDING', 'NO_CHANGE_EVIDENCE',
                              'RECHECK_NEEDED', 'RETRIEVAL_FAILED')),
    CONSTRAINT ck_gap_result_priority CHECK (priority IS NULL OR priority BETWEEN 1 AND 3)
);

CREATE TABLE IF NOT EXISTS analysis_evidence (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id BIGINT NOT NULL REFERENCES gap_result(result_id) ON DELETE CASCADE,
    rcept_no VARCHAR(20) NOT NULL,
    report_name TEXT,
    disclosed_at TIMESTAMPTZ,
    source_url TEXT,
    evidence_text TEXT,
    evidence_location TEXT,
    original_rcept_no VARCHAR(20),
    correction_details JSONB,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_analysis_evidence_result_receipt UNIQUE (result_id, rcept_no)
);

CREATE TABLE IF NOT EXISTS ai_generation_cache (
    cache_key CHAR(64) PRIMARY KEY,
    model VARCHAR(128) NOT NULL,
    response_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_comparison (
    comparison_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(company_id) ON DELETE RESTRICT,
    analysis_id BIGINT NOT NULL REFERENCES gap_analysis(analysis_id) ON DELETE CASCADE,
    analyzed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dart_only_summary TEXT NOT NULL,
    dart_only_source VARCHAR(30) NOT NULL,
    db_dart_snapshot JSONB NOT NULL,
    CONSTRAINT uq_analysis_comparison_analysis UNIQUE (analysis_id),
    CONSTRAINT ck_analysis_comparison_dart_source CHECK (
        dart_only_source IN ('OPENAI', 'GEMINI', 'UNAVAILABLE'))
);

ALTER TABLE analysis_comparison
    DROP CONSTRAINT IF EXISTS ck_analysis_comparison_dart_source;
ALTER TABLE analysis_comparison
    ADD CONSTRAINT ck_analysis_comparison_dart_source
    CHECK (dart_only_source IN ('OPENAI', 'GEMINI', 'UNAVAILABLE'));

CREATE TABLE IF NOT EXISTS consultation_question (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comparison_id BIGINT NOT NULL REFERENCES analysis_comparison(comparison_id) ON DELETE CASCADE,
    analysis_mode VARCHAR(20) NOT NULL,
    plan_id BIGINT REFERENCES rm_plan(plan_id) ON DELETE SET NULL,
    display_order SMALLINT NOT NULL,
    question_text TEXT NOT NULL,
    generation_source VARCHAR(30) NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_consultation_question_mode CHECK (
        analysis_mode IN ('AI_DART', 'DB_DART')),
    CONSTRAINT ck_consultation_question_generation_source CHECK (
        generation_source IN ('OPENAI', 'GEMINI', 'RULE_TEMPLATE'))
);

ALTER TABLE consultation_question
    DROP CONSTRAINT IF EXISTS ck_consultation_question_generation_source;
ALTER TABLE consultation_question
    ADD CONSTRAINT ck_consultation_question_generation_source
    CHECK (generation_source IN ('OPENAI', 'GEMINI', 'RULE_TEMPLATE'));

CREATE TABLE IF NOT EXISTS consultation_answer (
    answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL UNIQUE REFERENCES consultation_question(question_id) ON DELETE CASCADE,
    answer_text TEXT NOT NULL,
    answered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consultation_record (
    consultation_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(company_id) ON DELETE RESTRICT,
    consultation_date DATE NOT NULL,
    consultation_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_consultation_record_text CHECK (length(trim(consultation_text)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_rm_plan_company ON rm_plan(company_id);
CREATE INDEX IF NOT EXISTS idx_rm_plan_company_domain ON rm_plan(company_id, domain);
CREATE INDEX IF NOT EXISTS idx_gap_analysis_company_time ON gap_analysis(company_id, analysis_at DESC);
CREATE INDEX IF NOT EXISTS idx_gap_result_analysis ON gap_result(analysis_id);
CREATE INDEX IF NOT EXISTS idx_analysis_evidence_result ON analysis_evidence(result_id);
CREATE INDEX IF NOT EXISTS idx_analysis_comparison_company_time
    ON analysis_comparison(company_id, analyzed_at DESC);
CREATE INDEX IF NOT EXISTS idx_consultation_question_comparison
    ON consultation_question(comparison_id, analysis_mode, display_order);
CREATE INDEX IF NOT EXISTS idx_ai_generation_cache_expires
    ON ai_generation_cache(expires_at);
CREATE INDEX IF NOT EXISTS idx_consultation_record_company_date
    ON consultation_record(company_id, consultation_date DESC, consultation_record_id DESC);

CREATE TABLE IF NOT EXISTS rm_plan_import (
    company_id VARCHAR(64) NOT NULL,
    corp_code VARCHAR(8) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    consultation_date DATE,
    domain VARCHAR(32) NOT NULL,
    plan_id VARCHAR(128) NOT NULL,
    scope TEXT,
    knowledge_status VARCHAR(32) NOT NULL,
    plan_status VARCHAR(32) NOT NULL,
    last_confirmed_at TIMESTAMPTZ,
    amount NUMERIC(20, 2),
    currency VARCHAR(3),
    expected_at VARCHAR(128),
    expected_at_precision VARCHAR(20),
    source VARCHAR(255),
    evidence_level VARCHAR(32) NOT NULL,
    source_reference TEXT,
    valid_until DATE,
    review_due_at DATE,
    validity_status VARCHAR(32) NOT NULL,
    recorded_at TIMESTAMPTZ,
    note TEXT,
    rm_memo TEXT,
    CONSTRAINT uq_rm_plan_import_company_plan UNIQUE (company_id, plan_id)
);
